/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author Ben
 */
public class ThreadStatePanel extends javax.swing.JPanel {

    /**
     * Creates new form ThreadStatePanel
     */
    public ThreadStatePanel(String text) {
        initComponents();
        lbThreadName.setOpaque(true);
        lbThreadName.setText(text);
        this.setVisible(true);
        this.setNotUsed();
    }
    
    
    public void setRunning(){
        lbThreadName.setBackground(Color.green);
    }
    
    public void setWaiting(){
        lbThreadName.setBackground(Color.red);
    }
    
    public void setNotUsed(){
        lbThreadName.setBackground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbThreadName = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 1));

        lbThreadName.setText("jLabel1");
        add(lbThreadName);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbThreadName;
    // End of variables declaration//GEN-END:variables
}
